PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE User(id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, username VARCHAR(20) NOT NULL, password CHAR(32) NOT NULL, privilege INT NOT NULL);
INSERT INTO "User" VALUES(1,'root','63A9F0EA7BB98050796B649E85481845', 1);
DELETE FROM sqlite_sequence;
INSERT INTO "sqlite_sequence" VALUES('User',1);
COMMIT;
